"""create estimations table

Revision ID: b6b6198a3c77
Revises: 71590256c851
Create Date: 2026-09-16 11:35:09.423254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b6198a3c77'
down_revision: Union[str, Sequence[str], None] = '71590256c851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inquiries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interfaces', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('environment_complexity', sa.Integer(), nullable=False),
    sa.Column('project_mode', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('salary_per_month', sa.Integer(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('ufp', sa.Integer(), nullable=False),
    sa.Column('tcf', sa.Float(), nullable=False),
    sa.Column('fp', sa.Float(), nullable=False),
    sa.Column('effort_person_months', sa.Float(), nullable=False),
    sa.Column('time_months', sa.Float(), nullable=False),
    sa.Column('time_formatted', sa.String(length=100), nullable=False),
    sa.Column('cost_rupees', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimations')
    # ### end Alembic commands ###
